// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ModuleDiemDanhDbContext))]
    [Migration("20250527030959_khanh")]
    partial class khanh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Data.BanDaoTao", b =>
                {
                    b.Property<Guid>("IdBanDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaBanDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBanDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("VaiTroIdVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdBanDaoTao");

                    b.HasIndex("VaiTroIdVaiTro");

                    b.ToTable("BanDaoTaos");
                });

            modelBuilder.Entity("API.Data.BoMonCoSo", b =>
                {
                    b.Property<Guid>("IdBoMonCoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoSoIdCoSo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdBoMon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCoSo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdBoMonCoSo");

                    b.HasIndex("CoSoIdCoSo");

                    b.HasIndex("IdBoMon");

                    b.ToTable("BoMonCoSos");
                });

            modelBuilder.Entity("API.Data.CaHoc", b =>
                {
                    b.Property<Guid>("IdCaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("caHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCaHoc");

                    b.ToTable("CaHocs");
                });

            modelBuilder.Entity("API.Data.CapDoDuAn", b =>
                {
                    b.Property<Guid>("IdCDDA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCapDoDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCapDoDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdCDDA");

                    b.ToTable("CapDoDuAns");
                });

            modelBuilder.Entity("API.Data.CoSo", b =>
                {
                    b.Property<Guid>("IdCoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaHocIdCaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiaDiemIdDiaDiem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IPIdIP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDiaDiem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdIP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdCoSo");

                    b.HasIndex("CaHocIdCaHoc");

                    b.HasIndex("DiaDiemIdDiaDiem");

                    b.HasIndex("IPIdIP");

                    b.ToTable("CoSos");
                });

            modelBuilder.Entity("API.Data.DiaDiem", b =>
                {
                    b.Property<Guid>("IdDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BanKinh")
                        .HasColumnType("float");

                    b.Property<double?>("KinhDo")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<double?>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("IdDiaDiem");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("API.Data.DiemDanh", b =>
                {
                    b.Property<Guid>("IdDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhomXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSinhVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDiemDanh");

                    b.HasIndex("IdCaHoc");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdNhomXuong");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("API.Data.DuAn", b =>
                {
                    b.Property<Guid>("IdDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapDoDuAnIdCDDA")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdBoMon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCDDA")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHocKy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdDuAn");

                    b.HasIndex("CapDoDuAnIdCDDA");

                    b.HasIndex("IdBoMon");

                    b.HasIndex("IdHocKy");

                    b.ToTable("DuAns");
                });

            modelBuilder.Entity("API.Data.HocKy", b =>
                {
                    b.Property<Guid>("IdHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHocKy");

                    b.ToTable("hocKy");
                });

            modelBuilder.Entity("API.Data.IP", b =>
                {
                    b.Property<Guid>("IdIP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IP_DaiIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KieuIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdIP");

                    b.ToTable("IPs");
                });

            modelBuilder.Entity("API.Data.KHNXCaHoc", b =>
                {
                    b.Property<Guid>("IdNXCH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Buoi")
                        .HasColumnType("int");

                    b.Property<Guid?>("CoSoIdCoSo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiemDanhTre")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdCaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKHNX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkOnline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNXCH");

                    b.HasIndex("CoSoIdCoSo");

                    b.HasIndex("IdCaHoc");

                    b.HasIndex("IdKHNX");

                    b.ToTable("KHNXCaHocs");
                });

            modelBuilder.Entity("API.Data.KeHoach", b =>
                {
                    b.Property<Guid>("IdKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DuAnIdDuAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDuAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDienRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKeHoach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdKeHoach");

                    b.HasIndex("DuAnIdDuAn");

                    b.ToTable("KeHoachs");
                });

            modelBuilder.Entity("API.Data.KeHoachNhomXuong", b =>
                {
                    b.Property<Guid>("IdKHNX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKeHoach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhomXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoBuoi")
                        .HasColumnType("int");

                    b.Property<int>("SoSinhVien")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianThucTe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdKHNX");

                    b.HasIndex("IdKeHoach");

                    b.HasIndex("IdNhomXuong");

                    b.ToTable("KeHoachNhomXuongs");
                });

            modelBuilder.Entity("API.Data.LichGiangDay", b =>
                {
                    b.Property<Guid>("IdLichDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HTGiangDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdDiaDiem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDuAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNXCH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhomXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TTDiemDanh")
                        .HasColumnType("bit");

                    b.Property<bool>("TTDiemDanhMuon")
                        .HasColumnType("bit");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdLichDay");

                    b.HasIndex("IdDiaDiem");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdNXCH");

                    b.HasIndex("IdNhomXuong");

                    b.ToTable("LichGiangDays");
                });

            modelBuilder.Entity("API.Data.LichHoc", b =>
                {
                    b.Property<Guid>("IDLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaHocIdCaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocKyIdHocKy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDHocKy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNXCH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhomXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDLichHoc");

                    b.HasIndex("CaHocIdCaHoc");

                    b.HasIndex("HocKyIdHocKy");

                    b.HasIndex("IDHocKy");

                    b.HasIndex("IdNXCH");

                    b.HasIndex("IdNhomXuong");

                    b.ToTable("LichHocs");
                });

            modelBuilder.Entity("API.Data.LichSuDiemDanh", b =>
                {
                    b.Property<Guid>("IdLSDD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdDiemDanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNXCH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungBuoiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDiemDanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiDuyet")
                        .HasColumnType("int");

                    b.HasKey("IdLSDD");

                    b.HasIndex("IdDiemDanh");

                    b.HasIndex("IdNXCH");

                    b.ToTable("LichSuDiemDanhs");
                });

            modelBuilder.Entity("API.Data.NhomXuong", b =>
                {
                    b.Property<Guid>("IdNhomXuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DuAnIdDuAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdBoMon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDuAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhuTrachXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhomXuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNhomXuong");

                    b.HasIndex("DuAnIdDuAn");

                    b.HasIndex("IdBoMon");

                    b.HasIndex("IdPhuTrachXuong");

                    b.ToTable("NhomXuongs");
                });

            modelBuilder.Entity("API.Data.PhuTrachXuong", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailFE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailFPT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdCoSo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdCoSo");

                    b.ToTable("PhuTrachXuongs");
                });

            modelBuilder.Entity("API.Data.QuanLyBoMon", b =>
                {
                    b.Property<Guid>("IDBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoSoHoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBoMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDBoMon");

                    b.ToTable("QuanLyBoMons");
                });

            modelBuilder.Entity("API.Data.SinhVien", b =>
                {
                    b.Property<Guid>("IdSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNhomXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhomXuongIdNhomXuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<Guid>("VaiTroIdVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSinhVien");

                    b.HasIndex("NhomXuongIdNhomXuong");

                    b.HasIndex("VaiTroIdVaiTro");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("API.Data.VaiTro", b =>
                {
                    b.Property<Guid>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("API.Data.VaiTroNhanVien", b =>
                {
                    b.Property<Guid>("IdVTNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PhuTrachXuongIdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdVTNV");

                    b.HasIndex("IdVaiTro");

                    b.HasIndex("PhuTrachXuongIdNhanVien");

                    b.ToTable("VaiTroNhanViens");
                });

            modelBuilder.Entity("API.Data.BanDaoTao", b =>
                {
                    b.HasOne("API.Data.VaiTro", "VaiTro")
                        .WithMany("BanDaoTaos")
                        .HasForeignKey("VaiTroIdVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("API.Data.BoMonCoSo", b =>
                {
                    b.HasOne("API.Data.CoSo", "CoSo")
                        .WithMany("BoMonCoSos")
                        .HasForeignKey("CoSoIdCoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.QuanLyBoMon", "QuanLyBoMon")
                        .WithMany("BoMonCoSos")
                        .HasForeignKey("IdBoMon");

                    b.Navigation("CoSo");

                    b.Navigation("QuanLyBoMon");
                });

            modelBuilder.Entity("API.Data.CoSo", b =>
                {
                    b.HasOne("API.Data.CaHoc", "CaHoc")
                        .WithMany("CoSos")
                        .HasForeignKey("CaHocIdCaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.DiaDiem", "DiaDiem")
                        .WithMany("CoSos")
                        .HasForeignKey("DiaDiemIdDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.IP", "IP")
                        .WithMany("CoSos")
                        .HasForeignKey("IPIdIP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaHoc");

                    b.Navigation("DiaDiem");

                    b.Navigation("IP");
                });

            modelBuilder.Entity("API.Data.DiemDanh", b =>
                {
                    b.HasOne("API.Data.CaHoc", "CaHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdCaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.PhuTrachXuong", "PhuTrachXuong")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.NhomXuong", "NhomXuong")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdNhomXuong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.SinhVien", "SinhVien")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaHoc");

                    b.Navigation("NhomXuong");

                    b.Navigation("PhuTrachXuong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("API.Data.DuAn", b =>
                {
                    b.HasOne("API.Data.CapDoDuAn", "CapDoDuAn")
                        .WithMany("DuAns")
                        .HasForeignKey("CapDoDuAnIdCDDA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.QuanLyBoMon", "QuanLyBoMon")
                        .WithMany("DuAns")
                        .HasForeignKey("IdBoMon");

                    b.HasOne("API.Data.HocKy", "HocKy")
                        .WithMany("DuAns")
                        .HasForeignKey("IdHocKy");

                    b.Navigation("CapDoDuAn");

                    b.Navigation("HocKy");

                    b.Navigation("QuanLyBoMon");
                });

            modelBuilder.Entity("API.Data.KHNXCaHoc", b =>
                {
                    b.HasOne("API.Data.CoSo", null)
                        .WithMany("KHNXCaHocs")
                        .HasForeignKey("CoSoIdCoSo");

                    b.HasOne("API.Data.CaHoc", "CaHoc")
                        .WithMany("KHNXCaHocs")
                        .HasForeignKey("IdCaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.KeHoachNhomXuong", "KeHoachNhomXuong")
                        .WithMany("KHNXCaHocs")
                        .HasForeignKey("IdKHNX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaHoc");

                    b.Navigation("KeHoachNhomXuong");
                });

            modelBuilder.Entity("API.Data.KeHoach", b =>
                {
                    b.HasOne("API.Data.DuAn", "DuAn")
                        .WithMany()
                        .HasForeignKey("DuAnIdDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("API.Data.KeHoachNhomXuong", b =>
                {
                    b.HasOne("API.Data.KeHoach", "KeHoach")
                        .WithMany("KeHoachNhomXuongs")
                        .HasForeignKey("IdKeHoach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.NhomXuong", "NhomXuong")
                        .WithMany("KeHoachNhomXuongs")
                        .HasForeignKey("IdNhomXuong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeHoach");

                    b.Navigation("NhomXuong");
                });

            modelBuilder.Entity("API.Data.LichGiangDay", b =>
                {
                    b.HasOne("API.Data.DiaDiem", "DiaDiem")
                        .WithMany("LichGiangDays")
                        .HasForeignKey("IdDiaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.DuAn", "DuAn")
                        .WithMany("LichGiangDays")
                        .HasForeignKey("IdDuAn");

                    b.HasOne("API.Data.KHNXCaHoc", "KHNXCaHoc")
                        .WithMany("LichGiangDays")
                        .HasForeignKey("IdNXCH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.NhomXuong", "NhomXuong")
                        .WithMany("LichGiangDays")
                        .HasForeignKey("IdNhomXuong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("DuAn");

                    b.Navigation("KHNXCaHoc");

                    b.Navigation("NhomXuong");
                });

            modelBuilder.Entity("API.Data.LichHoc", b =>
                {
                    b.HasOne("API.Data.CaHoc", null)
                        .WithMany("LichHocs")
                        .HasForeignKey("CaHocIdCaHoc");

                    b.HasOne("API.Data.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("HocKyIdHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.DuAn", "DuAn")
                        .WithMany("LichHocs")
                        .HasForeignKey("IDHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.KHNXCaHoc", "KHNXCaHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("IdNXCH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.NhomXuong", "NhomXuong")
                        .WithMany("LichHocs")
                        .HasForeignKey("IdNhomXuong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("HocKy");

                    b.Navigation("KHNXCaHoc");

                    b.Navigation("NhomXuong");
                });

            modelBuilder.Entity("API.Data.LichSuDiemDanh", b =>
                {
                    b.HasOne("API.Data.DiemDanh", "DiemDanh")
                        .WithMany("LichSuDiemDanhs")
                        .HasForeignKey("IdDiemDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.KHNXCaHoc", "KHNXCaHoc")
                        .WithMany("LichSuDiemDanhs")
                        .HasForeignKey("IdNXCH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiemDanh");

                    b.Navigation("KHNXCaHoc");
                });

            modelBuilder.Entity("API.Data.NhomXuong", b =>
                {
                    b.HasOne("API.Data.DuAn", "DuAn")
                        .WithMany("NhomXuongs")
                        .HasForeignKey("DuAnIdDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.QuanLyBoMon", "QuanLyBoMon")
                        .WithMany("NhomXuongs")
                        .HasForeignKey("IdBoMon");

                    b.HasOne("API.Data.PhuTrachXuong", "PhuTrachXuong")
                        .WithMany("NhomXuongs")
                        .HasForeignKey("IdPhuTrachXuong");

                    b.Navigation("DuAn");

                    b.Navigation("PhuTrachXuong");

                    b.Navigation("QuanLyBoMon");
                });

            modelBuilder.Entity("API.Data.PhuTrachXuong", b =>
                {
                    b.HasOne("API.Data.CoSo", "CoSo")
                        .WithMany("PhuTrachXuongs")
                        .HasForeignKey("IdCoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoSo");
                });

            modelBuilder.Entity("API.Data.SinhVien", b =>
                {
                    b.HasOne("API.Data.NhomXuong", "NhomXuong")
                        .WithMany("SinhViens")
                        .HasForeignKey("NhomXuongIdNhomXuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.VaiTro", "VaiTro")
                        .WithMany("SinhViens")
                        .HasForeignKey("VaiTroIdVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomXuong");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("API.Data.VaiTroNhanVien", b =>
                {
                    b.HasOne("API.Data.VaiTro", "VaiTro")
                        .WithMany("VaiTroNhanViens")
                        .HasForeignKey("IdVaiTro");

                    b.HasOne("API.Data.PhuTrachXuong", "PhuTrachXuong")
                        .WithMany()
                        .HasForeignKey("PhuTrachXuongIdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuTrachXuong");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("API.Data.CaHoc", b =>
                {
                    b.Navigation("CoSos");

                    b.Navigation("DiemDanhs");

                    b.Navigation("KHNXCaHocs");

                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("API.Data.CapDoDuAn", b =>
                {
                    b.Navigation("DuAns");
                });

            modelBuilder.Entity("API.Data.CoSo", b =>
                {
                    b.Navigation("BoMonCoSos");

                    b.Navigation("KHNXCaHocs");

                    b.Navigation("PhuTrachXuongs");
                });

            modelBuilder.Entity("API.Data.DiaDiem", b =>
                {
                    b.Navigation("CoSos");

                    b.Navigation("LichGiangDays");
                });

            modelBuilder.Entity("API.Data.DiemDanh", b =>
                {
                    b.Navigation("LichSuDiemDanhs");
                });

            modelBuilder.Entity("API.Data.DuAn", b =>
                {
                    b.Navigation("LichGiangDays");

                    b.Navigation("LichHocs");

                    b.Navigation("NhomXuongs");
                });

            modelBuilder.Entity("API.Data.HocKy", b =>
                {
                    b.Navigation("DuAns");
                });

            modelBuilder.Entity("API.Data.IP", b =>
                {
                    b.Navigation("CoSos");
                });

            modelBuilder.Entity("API.Data.KHNXCaHoc", b =>
                {
                    b.Navigation("LichGiangDays");

                    b.Navigation("LichHocs");

                    b.Navigation("LichSuDiemDanhs");
                });

            modelBuilder.Entity("API.Data.KeHoach", b =>
                {
                    b.Navigation("KeHoachNhomXuongs");
                });

            modelBuilder.Entity("API.Data.KeHoachNhomXuong", b =>
                {
                    b.Navigation("KHNXCaHocs");
                });

            modelBuilder.Entity("API.Data.NhomXuong", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("KeHoachNhomXuongs");

                    b.Navigation("LichGiangDays");

                    b.Navigation("LichHocs");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("API.Data.PhuTrachXuong", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("NhomXuongs");
                });

            modelBuilder.Entity("API.Data.QuanLyBoMon", b =>
                {
                    b.Navigation("BoMonCoSos");

                    b.Navigation("DuAns");

                    b.Navigation("NhomXuongs");
                });

            modelBuilder.Entity("API.Data.SinhVien", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("API.Data.VaiTro", b =>
                {
                    b.Navigation("BanDaoTaos");

                    b.Navigation("SinhViens");

                    b.Navigation("VaiTroNhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
